version: '3'
services:
  rstudio:
    build: .
    image: ichiharanaruki/study:latest
    container_name: study
    environment: 
      - PASSWORD=0000
    ports:
      - 8787:8787
    volumes:
      - ../:/home/rstudio
    tty: true
    stdin_open: true